### ISSUE TITLE
Lmfao

### ISSUE THREAD

**Issue by RickyTheRacc** [Vagdedes/Spartan-AntiCheat#1]
<img width="1439" alt="WebWNNy-1" src="https://github.com/Vagdedes/Spartan-AntiCheat/assets/80427814/eeb30367-6be0-4379-a245-baa180e0fd73">

"If sueing you fails then I'll report your discord server for calling my objectively bad code badly coded!!" 

I'm not even involved with anticheats, you're just straight up handling this so poorly it's spreading through word of mouth 💀 stop now and save some dignity

**Comment by DAMcraft** [comment]
Bro he's gonna sue you now and report you to GitHub

**Comment by RickyTheRacc** [comment]
![20231002_143153](https://github.com/Vagdedes/Spartan-AntiCheat/assets/80427814/188f5978-ef7b-47f1-ab20-77d8465d8bfe)
