### ISSUE TITLE
GhostHand/Fastbreak false positive with haste effect

### ISSUE THREAD

**Issue by Alcrafter-YT** [Vagdedes/Spartan-AntiCheat#30]
Customer experienced false positives with fastbreak and ghosthand checks with haste effect and efficiency enchantment. 

Notifications:
![image-4](https://github.com/Vagdedes/Spartan-AntiCheat/assets/64634451/884c0e12-a859-4c8a-b528-d09b884aedf0)
![image-5](https://github.com/Vagdedes/Spartan-AntiCheat/assets/64634451/1b50da5d-1f18-416f-9c43-b281ee001c41)

Server version: Paper 1.20.6
Spartan version: 536.2
No incompatibilities known

Ticket URL: https://discord.com/channels/289384242075533313/1258010450386358343

**Comment by Alcrafter-YT** [comment]
Another customer experienced similar issues. Serverversion 1.20.6

Clip: https://medal.tv/games/minecraft/clips/icooo1oG0vE2s2E-9/d1337h5spUY7?invite=cr-MSx0Qk0sMTg1MTE1Miw

Log: 
[customerlog.txt](https://github.com/user-attachments/files/16096413/customerlog.txt)

**Comment by Vagdedes** [comment]
Fixed for the next update
