### ISSUE TITLE
SourceCode Problem

### ISSUE THREAD

**Issue by steffqxyz** [Vagdedes/Spartan-AntiCheat#55]
These 3 classes use a package that does not exists in the sourcecode 

package: `com.vagdedes.spartan.abstraction.check.implementation`

[Join](https://github.com/Vagdedes/Spartan-AntiCheat/blob/49ee9b1e85453adf2b5abfbf76a142df277df885/src/main/java/com/vagdedes/spartan/listeners/protocol/Join.java#L8)
[BackgroundMove](https://github.com/Vagdedes/Spartan-AntiCheat/blob/49ee9b1e85453adf2b5abfbf76a142df277df885/src/main/java/com/vagdedes/spartan/listeners/protocol/move/BackgroundMove.java#L6)
[Enums](https://github.com/Vagdedes/Spartan-AntiCheat/blob/49ee9b1e85453adf2b5abfbf76a142df277df885/src/main/java/me/vagdedes/spartan/system/Enums.java#L136)

**Comment by Vagdedes** [comment]
Fixed for the next update. Enums class will always contain imports from classes that don't exist, that's why we prompt you to change it.
