### ISSUE TITLE
PlayerStayEvent not being called

### ISSUE THREAD

**Issue by Vagdedes** [Vagdedes/Spartan-AntiCheat#6]
Package: com.vagdedes.spartan.listeners.protocol
Class: Shared
Method: stay
Issue: Is not called anywhere since the recent update of packets

`public static void stay(PlayerStayEvent e) {
        SpartanPlayer p = SpartanBukkit.getPlayer(e.getPlayer());
        p.getExecutor(Enums.HackType.Speed).handle(false, e);
    }`

**Comment by kireikosasha** [comment]
It's not a bug, it's a feature 👿
