### ISSUE TITLE
Water near Chest Falses

### ISSUE THREAD

**Issue by Barpadzik** [Vagdedes/Spartan-AntiCheat#62]
https://github.com/user-attachments/assets/e82198a0-327d-4f22-91c7-bcb1757583fe

**Comment by Vagdedes** [comment]
Cannot reproduce.

Which version of MC did you use?
Did you try without mods?

**Comment by Barpadzik** [comment]
1.21.2 ViaVersion Mod, I will try later without mods

**Comment by Barpadzik** [comment]
Can't reproduce 1.21.1 Vanilla, probably ViaVersion Mod Fault
