### ISSUE TITLE
Spartan bedrock always notify me that it bedrock only

### ISSUE THREAD

**Issue by Josh65-2201** [Vagdedes/Spartan-AntiCheat#66]
I have disabled all notifications in the config and restart my server yet it still shows the bedrock only message.

Version:
Plugin: 538.1
Minecraft: Paper 1.20.6 build 151

**Comment by Barpadzik** [comment]
Hi, what version of Spartan do you use? Do you own both versions?

**Comment by Josh65-2201** [comment]
I only have bedrock version

**Comment by Josh65-2201** [comment]
I can't get screen shot but this is what the log show

[Spartan Bedrock Notification] 
Hey, just a heads up! You have Java players which cannot be checked by the anti-cheat due to missing Java detections. Click https://polymart.org/resource/3600 to fix this.

**Comment by Josh65-2201** [comment]
It's now it sending 2 blank lines every so often
