### ISSUE TITLE
Message's sent force close the chat or UIs open

### ISSUE THREAD

**Issue by Josh65-2201** [Vagdedes/Spartan-AntiCheat#67]
This is the only plugin that I have had force close other UI for messages, It should just send the message

**Comment by Vagdedes** [comment]
Please elaborate

**Comment by Josh65-2201** [comment]
In what way, if spartan sends a message to me chat and any chest UI from plugins or Minecraft close. Turning them off doesn't work either as this still happens https://github.com/Vagdedes/Spartan-AntiCheat/issues/66#issuecomment-2510161210

**Comment by Vagdedes** [comment]
Some of our messages close the player's inventory/chat, will look into it.
