### ISSUE TITLE
Constant high ping and timeouts on Java with version 538.7

### ISSUE THREAD

**Issue by Josh65-2201** [Vagdedes/Spartan-AntiCheat#68]
## Description
Java players are constantly lagging with ping in the 1000s and often time out. This doesn't happen with 538.6

## Logs
Most times there is lots of teleports shown in console
[error.txt](https://github.com/user-attachments/files/18169296/error.txt)

## Versions
Plugin: 538.7 Bedrock only
Server: Paper 1.20.6 build 151

**Comment by Vagdedes** [comment]
Hi, is this the issue we recently solved over Discord?

**Comment by Josh65-2201** [comment]
I haven't been on your Discord server so I don't know

**Comment by Vagdedes** [comment]
Was ProtocolLib being used?
About how many players were online at the time?

**Comment by Josh65-2201** [comment]
v5.3.0 and it happens with just me online or more

**Comment by Vagdedes** [comment]
Do you have a Discord where can can conduct some testing?

**Comment by Josh65-2201** [comment]
Yes, I can make a thread in support channel

**Comment by Vagdedes** [comment]
Please do so

**Comment by Vagdedes** [comment]
Issue moved to Discord
