### ISSUE TITLE
Speed false positive for beacon

### ISSUE THREAD

**Issue by kepa2018** [Vagdedes/Spartan-AntiCheat#8]
I made a new test server running the current version of Spigot with Spartan as the only plugin.  When I made a beacon, set it to speed, and ran, it flagged my character for speed cheats.
![beacon_speed_Spartan](https://github.com/Vagdedes/Spartan-AntiCheat/assets/173075423/25271cce-0912-4992-8d0e-f1d2f4bda5aa)

**Comment by kireikosasha** [comment]
fixed to next update

**Comment by Vagdedes** [comment]
> fixed to next update

for* my non-English friend :P
